const locator = require('../bluestone-locator.js');
const projectFunc = require('../bluestone-func.js');
const puppeteer = require('puppeteer');
const bluestoneFunc = require('bluestone/ptLibrary/bluestone-func');
const config = require('../config.js');
const bluestoneType = require('bluestone/ptLibrary/class/index');
describe('Testing722814', () => {
    it('Testing722814', async function () {
        let element, vars, frame;
        const browser = await puppeteer.launch(config.puppeteer);
        const page = await browser.newPage();
        vars = new bluestoneType.VarSaver(__filename, this.runnable().currentRetry());
        frame = page;
        await bluestoneFunc.initialize.func(vars, page);
        await bluestoneFunc.goto.func(frame, 'http://pa-frontend-qe.eastus.azurecontainer.io/home');
        await bluestoneFunc.waitElementExists.func(frame, locator['Txt User Name'], 8054, vars.getSnapshot('Bluestone-Snapshot-1'));
        await bluestoneFunc.click.func(frame, locator['Txt User Name']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Txt User Name'], 4043, vars.getSnapshot('Bluestone-Snapshot-3'));
        await bluestoneFunc.change.func(frame, locator['Txt User Name'], 'demo');
        await bluestoneFunc.waitElementExists.func(frame, locator['Txt Password'], 3000, vars.getSnapshot('Bluestone-Snapshot-5'));
        await bluestoneFunc.click.func(frame, locator['Txt Password']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Txt Password'], 3558, vars.getSnapshot('Bluestone-Snapshot-7'));
        await bluestoneFunc.change.func(frame, locator['Txt Password'], 'demo');
        await bluestoneFunc.waitElementExists.func(frame, locator['Btn Login'], 3000, vars.getSnapshot('Bluestone-Snapshot-9'));
        await bluestoneFunc.click.func(frame, locator['Btn Login']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Opt WorkFlow'], 3000, vars.getSnapshot('Bluestone-Snapshot-11'));
        await bluestoneFunc.click.func(frame, locator['Opt WorkFlow']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Link NewWorkflow 159'], 3734, vars.getSnapshot('Bluestone-Snapshot-13'));
        await bluestoneFunc.click.func(frame, locator['Link NewWorkflow 159']);
        await bluestoneFunc.waitElementExists.func(frame, locator['DrawElement 1'], 3000, vars.getSnapshot('Bluestone-Snapshot-15'));
        await bluestoneFunc.click.func(frame, locator['DrawElement 1']);
        await bluestoneFunc.waitElementExists.func(frame, locator['DrawElementItem Remove'], 3000, vars.getSnapshot('Bluestone-Snapshot-17'));
        await bluestoneFunc.click.func(frame, locator['DrawElementItem Remove']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Btn Save'], 26805, vars.getSnapshot('Bluestone-Snapshot-19'));
        await bluestoneFunc.click.func(frame, locator['Btn Save']);
        await bluestoneFunc.waitElementExists.func(frame, locator['Btn Cancel'], 23069, vars.getSnapshot('Bluestone-Snapshot-21'));
        await bluestoneFunc.click.func(frame, locator['Btn Cancel']);
    }).timeout(9999999);
});